# Generated by Django 5.0.1 on 2024-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0002_comment_like_message_delete_feedsmodel_like_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.AddField(
            model_name='message',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
